services:
  nestjs:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app

  db:
    image: postgres:17.4-alpine3.21
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anti_fraud
    volumes:
      - postgres2_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres2_data:
